version: "3.8"

services:
  api:
    build: .
    container_name: borger_api
    ports:
      - "1425:1425"
    volumes:
      - ./datastore:/app/datastore
    command: uvicorn main:app --host 0.0.0.0 --port 1425
    restart: unless-stopped

  worker:
    build: .
    container_name: borger_worker
    volumes:
      - ./datastore:/app/datastore
    command: python worker.py
    restart: unless-stopped